### ISSUE TITLE
I am only getting the first header to display

### ISSUE THREAD

**Issue by rw86347** [afollestad/sectioned-recyclerview#14]
For some reason I am only getting the first header to be displayed. the debugger confirms that it is only asking about the first section header.

Here is my code...

`public class MyAdapter extends SectionedRecyclerViewAdapter<MyAdapter.MainVH> {
    private List<stereoInfo> contactList;
    private Context _context;

    public MyAdapter(List<stereoInfo> contactList, Context context) {
        this.contactList = contactList;
        _context = context;
    }

    @Override
    public int getSectionCount() {
        return 4;
    }

    @Override
    public int getItemCount(int i) {
        if (i == 0){
            return 10;
        }
        return contactList.size()-1;
    }

    public void onBindHeaderViewHolder(MainVH holder, int section) {
        // Setup header view.
        holder.vHeaderText.setText("section "+(section+1));
    }

    public void onBindViewHolder(MainVH holder, int section, int relativePosition, int absolutePosition) {
        // Setup non-header view.
        // 'section' is section index.
        // 'relativePosition' is index in this section.
        // 'absolutePosition' is index out of all non-header items.
        // See sample project for a visual of how these indices work.
        stereoInfo ci = contactList.get(absolutePosition);
        holder.vName.setText(ci.productName);
        holder.vPrice.setText("$"+ci.price);
        int resID = _context.getResources().getIdentifier(ci.picName, "drawable", "com.mountainstateconsulting.recyclerview");
        if (resID > 0){
            Bitmap bitmap = BitmapFactory.decodeResource(_context.getResources(), resID);
            holder.vPic.setImageBitmap(bitmap);
        }
    }

    @Override
    public MainVH onCreateViewHolder(ViewGroup parent, int viewType) {
        // Change inflated layout based on 'header'.
        View v = LayoutInflater.from(parent.getContext())
                .inflate(viewType == VIEW_TYPE_HEADER ? R.layout.header : R.layout.card_view, parent, false);
        return new MainVH(v);
    }

    public static class MainVH extends RecyclerView.ViewHolder {
        protected TextView vName;
        protected TextView vPrice;
        protected TextView vHeaderText;
        protected ImageView vPic;

        public MainVH(View v) {
            super(v);
            vName =  (TextView) v.findViewById(R.id.txtName);
            vPrice = (TextView)  v.findViewById(R.id.txtPrice);
            vPic = (ImageView)  v.findViewById(R.id.imageView);
            vHeaderText = (TextView) v.findViewById(R.id.headerText);
        }
    }
}`

**Comment by afollestad** [comment]
You probably need to enable displaying empty sections.
