### ISSUE TITLE
How do we implement onClick listener?

### ISSUE THREAD

**Issue by riinav** [afollestad/sectioned-recyclerview#15]
usually I use this code to implement click using [https://gist.github.com/lnikkila/d9493a0626e89059c6aa](https://gist.github.com/lnikkila/d9493a0626e89059c6aa)

but in our case the position is absolute, so cant get the item, 

I want to implement two different click listeners
- on section/header
- on child item

Can you help me with implementing click listeners

**Comment by diyaa-hamza** [comment]
`  public void onBindHeaderViewHolder(MainVH holder, final int section) {
 holder.title.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(context,"Section:" + section,Toast.LENGTH_SHORT).show();
            }
        }); }`

And For Item

`   public void onBindViewHolder(MainVH holder, int section, int relativePosition, int absolutePosition) {
 holder.title.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(context,"Item:" + relativePosition,Toast.LENGTH_SHORT).show();
            }
        });
}`

**Comment by diyaa-hamza** [comment]
`public interface RecyclerTouchListenerHeader {
    void onClick(int section);
}
`

In Adapter
` Context context;
    RecyclerTouchListenerHeader recyclerTouchListenerHeader;
    public MainAdapter(Context context,RecyclerTouchListenerHeader recyclerTouchListenerHeader) {
        //layoutInflater = LayoutInflater.from(context);
        this.context = context;
        this.recyclerTouchListenerHeader=recyclerTouchListenerHeader;
    }`

` holder.title.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                recyclerTouchListenerHeader.onClick(section);
            }
        });`


In Activity Class
`    adapter  = new MainAdapter(getApplicationContext(), new RecyclerTouchListenerHeader() {
            @Override
            public void onClick(int section) {
                Toast.makeText(getApplicationContext(),"Section:"+section,Toast.LENGTH_SHORT).show();
            }
        });`

**Comment by afollestad** [comment]
When using any form of a `RecyclerView`, it's up to your own implementation.

The "correct" way is generally to set the on click listener to the `itemView` from inside the `ViewHolder`. From inside the `ViewHolder`, you can use `getAdapterPosition()` to get the item index and pass it to the adapter, from which you can forward the event to the `Activity`.

**Comment by abhishekprince** [comment]
@afollestad main problem is `getAdapterPosition()` don't tell us section so we can't know which section items are clicked

**Comment by afollestad** [comment]
The latest release helps.

https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0

Checkout the sample project.
