### ISSUE TITLE
getItemId() support

### ISSUE THREAD

**Issue by duncanleo** [afollestad/sectioned-recyclerview#16]
Library version: 0.2.2

Is it possible to add `getItemId()` support? This introduces a unique `long` type id for each item, and is used in conjunction with `adapter.setHasStableIds(true)`. At the moment, I only have the absolute position, whereas I need the relative position.

Thanks! Your library has really helped! 😄

**Comment by mveroukis** [comment]
Isn't getItemId() just part of the base class? You should be able to just override that and make it return whatever ID you need to. My biggest beef with getItemId() is that it's restricted to just "long" types. My IDs are GUIDs, which don't map well to longs.

**Comment by duncanleo** [comment]
I'm afraid I did not explain this well enough above, but the support I needed in `getItemId()` was for differentiating between header and non-header items, as the item id I am generating is dependent on whether the item is a header.

As for the bit about it being restricted to the long type - is there any reason for that?

Thanks!

**Comment by mveroukis** [comment]
Well, there's a private member in the Sectioned adapter called: getSectionIndexAndRelativePosition(). Perhaps make that private and call that from your getItemId() override (not sure why it's private, it seems useful for derived classes).

As for the long type, that's Google's design decision, not sure how we could go about using different types for IDs. Perhaps a mapping of something like GUIDs to longs, but that seems yucky. Anyway, that's off topic, not sure why I brought it up.

**Comment by afollestad** [comment]
Thought I should mention that newer versions expose ID getters for headers and items.

**Comment by duncanleo** [comment]
@afollestad awesome, thank you for the heads-up and the new feature!
