### ISSUE TITLE
Add support for ItemDecorations

### ISSUE THREAD

**Issue by jahirfiquitiva** [afollestad/sectioned-recyclerview#17]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.
###### Include the following:
- Library version: `0.2.2`
- Device OS version: `6.0.1`
- Device Manufacturer: `Motorola`
- Device Name: `Moto G 2nd Gen`

Also, please wrap Java with correct syntax highlighting.

``` java
RecyclerView mRecyclerView = (RecyclerView) layout.findViewById(R.id.grid_rv);

GridLayoutManager gridManager = new GridLayoutManager(context, columnsNumber);

GridSpacingItemDecoration space = new GridSpacingItemDecoration(columnsNumber, gridSpacing, true);

SectionAdapter sectionAdapter = new SectionAdapter(context);

mRecyclerView.addItemDecoration(space);
mRecyclerView.setHasFixedSize(true);
mRecyclerView.setLayoutManager(gridManager);
sectionAdapter.setLayoutManager(gridManager);
mRecyclerView.setAdapter(sectionAdapter);
```
###### Information

I want my recycler view to use a custom item decoration for grid, which makes margins look good in all items, and be consistent.

Which is better because when you use margins in the items, they won't look consistent in the recycler view.

The code of the item decoration can be found [here](https://gist.github.com/jahirfiquitiva/1f93ed6bbe37286b71334a2e890a37ea).
###### Expected Result

**Portrait**
![screenshot_20160517-193220](https://cloud.githubusercontent.com/assets/10360816/15628222/6030ac7c-24c1-11e6-855b-c4f5a8cc8da4.png)

**Landscape**
![screenshot_20160517-193136](https://cloud.githubusercontent.com/assets/10360816/15628223/64213edc-24c1-11e6-8a5f-a05e610735e9.png)
###### Actual Result

**Portrait**
![screenshot_20160517-193203](https://cloud.githubusercontent.com/assets/10360816/15628227/6f88de24-24c1-11e6-9a5e-c1a7e25d3420.png)

**Landscape**
![screenshot_20160517-193053](https://cloud.githubusercontent.com/assets/10360816/15628228/75ba233e-24c1-11e6-983c-eb30c36e56ce.png)

**Comment by verheyefrancesco** [comment]
My ItemDecorator is looking good when I'm using this code:
`final GridLayoutManager gridLayoutManager = new GridLayoutManager(this.recyclerView.getContext(), COLUMNS_COUNT);
        gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                if(adapter.isHeader(position)){
                    return COLUMNS_COUNT;
                }
                return 1;
            }
        });`

**Comment by jahirfiquitiva** [comment]
@verheyefrancesco

What's your item decoration? Default one?

**Comment by verheyefrancesco** [comment]
@jahirfiquitiva 
https://gist.github.com/verheyefrancesco/627b951d700edc71374f04a6508be102

**Comment by jahirfiquitiva** [comment]
@verheyefrancesco can you share the code from ```adapter.headersBeforePosition(itemPosition)``` ... please?

Thanks.

**Comment by jahirfiquitiva** [comment]
@verheyefrancesco 

Can you share the code you use to get the number of headers before item position?

I mean the one you use to get the int here: 
```java
int headersBeforeItemPosition = this.adapter.headersBeforePosition(itemPosition);
```

Thanks in advance.

**Comment by verheyefrancesco** [comment]
`public int headersBeforePosition(int position) {
        int count = 0;
        for (Integer headerPosition : this.headerTitles.keySet()) {
            if (position > headerPosition) {
                count++;
            } else {
                return count;
            }
        }
        return count;
    }`

headersTitles is a HashMap<Integer, String> ==> Position, Title

**Comment by jahirfiquitiva** [comment]
@verheyefrancesco 
Doesn't seem to work for me.

@afollestad 
Any chance you could do something about it?

**Comment by afollestad** [comment]
There shouldn't be anything preventing item decorations from working; I don't do anything abnormal with the `RecyclerView` in this area.
