### ISSUE TITLE
UI disrupt

### ISSUE THREAD

**Issue by homedevs** [afollestad/sectioned-recyclerview#18]
Hi,

Your code exactly works in sample code but when I try to copy/paste your classes/adapter etc from sample to my project , UI is getting totally disrupt. Each item cover the whole screen,

I am using same XMLs provided by you. Any idea ?

Here are the few UI images,

![device-2016-06-08-085154](https://cloud.githubusercontent.com/assets/11264134/15881795/6fe55dbe-2d56-11e6-9872-f3558872ec52.png)
![device-2016-06-08-085236](https://cloud.githubusercontent.com/assets/11264134/15881802/7451509c-2d56-11e6-951a-c3a5aca4c134.png)

**Comment by afollestad** [comment]
If you're using a new version of RecyclerView, your list items have to have their height set to `wrap_content`.
