### ISSUE TITLE
Support for notifyDataSetChanged in section

### ISSUE THREAD

**Issue by sawcioo** [afollestad/sectioned-recyclerview#22]
Please add support for notifyDataSetChanged in section.

**Comment by stephenmcbride** [comment]
+1 Thanks!

**Comment by sunnykinger** [comment]
Yes I need this functionality. +1

**Comment by binu8051** [comment]
me too +1

**Comment by Evige** [comment]
yes +1

**Comment by afollestad** [comment]
Added

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0
