### ISSUE TITLE
How Add different object to this recycleView? 

### ISSUE THREAD

**Issue by jjimenez0611** [afollestad/sectioned-recyclerview#24]
Hi All

I really like this sectioned-recycleview, but a have some doubts. For example I have a class costumerRewards and other class like a merchantRewards, I want add in the first section a header and the list of customerRewards and then add in the other section another header and the list of merchantRewards. And then implement an onclick event to each reward to see the detail of the reward... 

I understand you basic example, but I really don't know how to implement with different objects list. 

I really appreciate if you can give me a some idea... Or if you have some example that I can see.. 

Best Regards.

**Comment by afollestad** [comment]
It's possible, but implementations are up to you.
