### ISSUE TITLE
Sections with timestamp like in Inbox

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/sectioned-recyclerview#26]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `0.2.3`

I need some ideas on how to create sections as shown in the image below:
![android_inbox_1](https://cloud.githubusercontent.com/assets/3120052/20646879/e7a4dc04-b4aa-11e6-8a14-31c73aae3a76.png)

I have made some progress but the result is to have something shown above with optimized code. Let me know your thoughts.

**Comment by afollestad** [comment]
Implementations are up to you.

**Comment by AkshayChordiya** [comment]
No problem. Thanks.
