### ISSUE TITLE
Relative position inside RecyclerView.ViewHolder

### ISSUE THREAD

**Issue by sunnykinger** [afollestad/sectioned-recyclerview#27]
I have my onClick listener setup inside onCreateViewHolder. There is a button which adds and deletes items when tapped so When I add items to a list for one particular section, it adds that item to the last, but I am facing problems while deleting an item from the list as in onCreateViewHolder I can only get the position using getAdapterPosition() method and it gives me absolute position so it is hard for me to delete an item from a particular list used for a particular section as calculations go wrong for the index.

Can anyone give me solution to the problem I m facing.

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0
