### ISSUE TITLE
The last section element jumps to 2nd last section on scrolling

### ISSUE THREAD

**Issue by AkshayChordiya** [afollestad/sectioned-recyclerview#28]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `0.2.3`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`

###### Code (Adapter)
```java

@Override
    public int getSectionCount() {
        return 5;
    }

    @Override
    public int getItemCount(int section) {
        int count;
        switch (section) {
            case TODAY:
                return (int) Stream.of(mMessages).map(Message::getTimeStamp).filter(DateUtils::isToday).count();
            case YESTERDAY:
                count = (int) Stream.of(mMessages).map(Message::getTimeStamp).filter(Utils::isYesterday).count();
            case WEEK:
                return (int) Stream.of(mMessages).map(Message::getTimeStamp).filter(Utils::isThisWeek).count();
            case MONTH:
                return (int) Stream.of(mMessages).map(Message::getTimeStamp).filter(Utils::isThisMonth).count();
            case OLDER:
                return (int) Stream.of(mMessages).map(Message::getTimeStamp).filter(Utils::isOlder).count();
            default:
                return 0;
        }
    }

    @Override
    public void onBindHeaderViewHolder(MessageViewHolder holder, int section) {
       // Setting header string from string array
        holder.title.setText(mContext.getResources().getStringArray(R.array.timestampHeaders)[section]);
    }

    @Override
    public void onBindViewHolder(MessageViewHolder holder, int section, int relativePosition, int absolutePosition) {
        if (absolutePosition < 0) {
            return;
        }
        final Message message = mMessages.get(absolutePosition);
        // MY LOGIC
    }

```
 
###### Reproduction Steps

1. Scroll 
2. Wait for sometime
3. Scroll again and bug

###### Expected Result
![notigo section original](https://cloud.githubusercontent.com/assets/3120052/20720135/1a27307a-b684-11e6-9592-8f8ccd5a5e2e.png)

###### Actual Result
![notigo section actual](https://cloud.githubusercontent.com/assets/3120052/20720154/224d6936-b684-11e6-86d6-988703952594.png)

**Comment by AkshayChordiya** [comment]
@afollestad Any comments on this issue?

**Comment by afollestad** [comment]
I started a new job two weeks ago so I don't have any time for OS projects right now.

---

Someone will have to contribute with PRs.

**Comment by AkshayChordiya** [comment]
@afollestad No problem. We will try to fix it. Thanks

**Comment by afollestad** [comment]
There is a new release available today.

I haven't experienced any issues similar to this one, though.
