### ISSUE TITLE
Create RecyclerView with multiple view types

### ISSUE THREAD

**Issue by mradzinski** [afollestad/sectioned-recyclerview#3]
Is there any way we might create a RecyclerView with multiple view types? I mean, you overrode *getItemViewType* inside *SectionedRecyclerViewAdapter* class, made it final and then deprecated it...

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.2.0

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0
