### ISSUE TITLE
 Get horizontally scrollable section items inside each section?

### ISSUE THREAD

**Issue by blood-mist** [afollestad/sectioned-recyclerview#32]
![wod_new_edited](https://cloud.githubusercontent.com/assets/16567969/22970004/9a96155e-f398-11e6-86d3-c6e5fc1c5976.png)
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

Thanks to your library ,my work has been much easier. As in the tutorial , I have used GridLayoutManager
to show section-items according to their respective Section-Header titles. 
But now, I have come across a new issue. I am required to make each section items horizontally scrollable. I tried a lot , but the only thing I came close to was being able to scroll the entire section horizontally.
What I need is Vertically scrollable sections with Horizontally scrollable section items.

Someone please help me with this.

Thank You.

**Comment by blood-mist** [comment]
Why has my issue not been replied? :(

**Comment by afollestad** [comment]
You'll need to handle this on your own using `NestedScrollView`'s or something similar.
