### ISSUE TITLE
Method to convert relative position to absolute position

### ISSUE THREAD

**Issue by mehdok** [afollestad/sectioned-recyclerview#33]
This is nice to have methods for converting absolute position to relative and vice versa.

**Comment by mr746866** [comment]
+1

**Comment by afollestad** [comment]
`getRelativePosition(int)` is now exposed from the adapter, `getRelativePosition()` is exposed from the `ViewHolder`.

I forgot to add a method to get an absolute position from relative, will do that for another release.

https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0

**Comment by afollestad** [comment]
Available in release 0.4.1.
