### ISSUE TITLE
Question, what is the structure of the list you are sending ?

### ISSUE THREAD

**Issue by mhdtouban** [afollestad/sectioned-recyclerview#36]
Hello,

How do you populate the data, I mean what is the structure of the list you are sending?
Are you sending ArrayList (A, List<b,b,b,b>,A,List<b,b,b,b> etc) or (A,b,A,b etc) ?

In my use case, I want to have a header of type A with 4 subitems of type B.

If I pass it two array lists one for headers and the other for items, I get indexoutofboundsexception in onBindViewHolder when trying to get item from itemsList.get(absolutePosition)

Thanks,

**Comment by blood-mist** [comment]
Just store all the arraylist in a hashmap.. get the arraylists from hashmap on bindviewholder.. you that's what I did
