### ISSUE TITLE
How to scroll to a specific section? 

### ISSUE THREAD

**Issue by abhishekprince** [afollestad/sectioned-recyclerview#37]
Suppose I have multiple sections so when my data is loaded from server I want to jump to a specific section . how can I achieve that?

**Comment by afollestad** [comment]
Scrolling is done from the `LayoutManager` rather than through the `Adapter`, so I cannot add scrolling logic into this library.

**Comment by afollestad** [comment]
However, in the next release, I've added a method to the adapter called `getSectionHeaderIndex()`. You could use that to get the position you wish to scroll to.

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.4.0

**Comment by abhishekprince** [comment]
@afollestad but can you provide me some logic to do it. I've tried a lot but not able to scroll on specific section?

**Comment by afollestad** [comment]
```java
int index = adapter.getSectionHeaderIndex(section);
layoutManager.scrollToPosition(index);
```

**Comment by abhishekprince** [comment]
@afollestad thanks bro ... very good library. I will always use this

**Comment by abhishekprince** [comment]
@afollestad thanks bro for replying but its not scrolling i don't know why..
