### ISSUE TITLE
Returnig two view holders

### ISSUE THREAD

**Issue by ambinabhi** [afollestad/sectioned-recyclerview#54]
I want to to return two view holders , the current implementation iextends SectionedRecyclerViewAdapter<MainAdapter.MainVH>,not able to separate headers from items , i need something like ''extends SectionedRecyclerViewAdapter<RecyclerView.ViewHolder>''. Any help is much appredciated.

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/issues/53
