### ISSUE TITLE
Is it possible to show the added section collapsed?

### ISSUE THREAD

**Issue by AngeloAvv** [afollestad/sectioned-recyclerview#56]
I was wondering if it is possible to you to implement a setter that let you add sections and show them collapsed by default.

I am trying to achieve this by combining these two instructions with no result since empty sections are visible instead of getting hidden.

`adapter.shouldShowHeadersForEmptySections(false);`
`adapter.collapseAllSections();`

**Comment by boswelja** [comment]
You can handle this yourself
1. Add the section to your list or whatever you're using to store sections
2. Call notifyItemAdded(<position of your item>)
3. Call collapseSection(<position of your item>)
