### ISSUE TITLE
setFullSpan in onBindViewHolder

### ISSUE THREAD

**Issue by TheAndroidMaster** [afollestad/sectioned-recyclerview#6]
Sorry for the random issue, but would it be possible to add support for making an item span the width of the screen from inside the adapter? I see you've added a method for [header items to do this](https://github.com/afollestad/sectioned-recyclerview/blob/master/library/src/main/java/com/afollestad/sectionedrecyclerview/SectionedRecyclerViewAdapter.java), but I would like to be able to do this with regular items as well.

**Comment by TheAndroidMaster** [comment]
I've managed to find a way around my problem using .setSpanSizeLookup on a gridlayoutmanager after passing it to the adapter, but this is still limited by the data method used. Since the position given by the span size lookup is affected by header items, for some usages of the adapter it would be impossible to get the item's type.

**Comment by shahimclt** [comment]
Yes I am also looking to achieve the exact same thing.
@afollestad great lib btw!

**Comment by afollestad** [comment]
I've added a method you can override (`getRowSpan(int, int, int, int)`). But it's not really a good idea to put a method like `setFullSpan(boolean)` in there. Changing span sizes would require refreshing the entire list, which would be inefficient and causes some issues (I tried it).

I've also fixed some issues for the newer versions of AppCompat.

**Comment by afollestad** [comment]
https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.2.1
