### ISSUE TITLE
How i can Create sectioned recyclerview With search form

### ISSUE THREAD

**Issue by khubbaib** [afollestad/sectioned-recyclerview#64]
How i can attach Search with  sectioned recyclerview so items can be search...
My current View is http://prntscr.com/h313sf
I want like this http://prntscr.com/h313n0

**Comment by AkshayChordiya** [comment]
I checked both the views. Your current view is pretty close what you want.  Just do some styling to the header layout and it will be done like setting the text to the center.
Meanwhile the search logic will be your own and **not part of the library**
