### ISSUE TITLE
Section RecyclerView by date

### ISSUE THREAD

**Issue by Andrew6868** [afollestad/sectioned-recyclerview#68]
Hello author,
Can we use this library to group recycle view items by date like following : 

 -- January 2016(Divider)--
--item #1--

--item #2--

--item #3--

-- December 2015(Divider)--
--item #4--

--item #5--

**Comment by afollestad** [comment]
That is the whole purpose of this library. Read the documentation.

**Comment by afollestad** [comment]
Implementation details are up to you.
