### ISSUE TITLE
Allow negative viewType?

### ISSUE THREAD

**Issue by dhiraj** [afollestad/sectioned-recyclerview#7]
```
@IntRange(
        from = 0L,
        to = 2147483647L
    )
    public int getItemViewType(int section, int relativePosition, int absolutePosition) {
        return -1;
    }
```

I'm trying to return the view type as the actual R.layout.id I want to inflate. That way, I wouldn't have to do unnecessary mappings. However, my layout ids are negative!

Is there any particular reason to have the current IntRange annotation set up to disallow negative ids? If not please allow negative ranges as well, thanks!

**Comment by d-fournier** [comment]
I think the developer has reserved the negative integers to his own ViewTypes like  `VIEW_TYPE_HEADER`. To avoid issues, he constraints you to use a positive value.
