### ISSUE TITLE
GridLayoutManager size on scroll issue

### ISSUE THREAD

**Issue by kylejablonski** [afollestad/sectioned-recyclerview#9]
Upon load of data into the RecyclerView, items appear to be loaded as expected, but once you scroll and the views are recycled, it displays the items with a large view size. 

For example, i have a header view which contains a TextView and a regular view which has an imageView inside a FrameLayout, once i scroll past my first section, all Views are sized to some random height. 

![mobile portrait copy](https://cloud.githubusercontent.com/assets/4803433/13933677/aa8d5af8-ef6b-11e5-893f-1a67756dd4ab.png)
![mobile portrait](https://cloud.githubusercontent.com/assets/4803433/13933678/aa8d989c-ef6b-11e5-87fa-a28c53342406.png)

**Comment by afollestad** [comment]
That's not any issue with this library.

Your views are probably measuring incorrectly. With newer versions of AppCompat/RecyclerView, list items need to use `wrap_content` for their height, too.

**Comment by kylejablonski** [comment]
Hey Aidan, I appreciate the quick response. I have both my header and list item views set to wrap_content and am still seeing the issue on my side. Any suggestions?

**Comment by afollestad** [comment]
I realized there was an issue in the library, it wasn't compatible with newer versions of AppCompat yet.

There's a new release now: https://github.com/afollestad/sectioned-recyclerview/releases/tag/0.2.1

**Comment by kylejablonski** [comment]
Awesome, thanks so much. It is working well now.

**Comment by afollestad** [comment]
Great! You're welcome
